version: "3"
services:
  oqt-workers:
    container_name: oqt-workers
    build:
      context: ./workers
      dockerfile: Dockerfile
    environment:
      OQT_DATA_DIR: /data
      OQT_LOG_LEVEL: INFO
      OHSOME_API: https://api.ohsome.org/v1/
      POSTGRES_DB: oqt
      POSTGRES_USER: oqt
      POSTGRES_PASSWORD: oqt
      POSTGRES_HOST: oqt-database
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA: public
    command: poetry run python scripts/start_api.py --host 0.0.0.0
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - oqt-dev-database
    depends_on:
      - oqt-database

  oqt-website:
    container_name: oqt-website
    build:
      context: website/
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./website/website:/usr/share/nginx/html
    depends_on:
      - oqt-workers

  oqt-database:
    container_name: oqt-database
    build:
      context: database/
      dockerfile: Dockerfile.development
      args:
        # Setup minimal database for running tests
        OQT_TEST_DB: "False"
    environment:
      POSTGRES_DB: oqt
      POSTGRES_USER: oqt
      POSTGRES_PASSWORD: oqt
    ports:
      - "5445:5432"
    networks:
      - oqt-dev-database
    volumes:
      - oqt-dev-pg_data:/var/lib/postgresql/data

networks:
  oqt-dev-database:

volumes:
  oqt-dev-pg_data:
