[tool.poetry]
name = "ohsome_quality_analyst"
version = "0.7.0"
description = "Intrinsic and extrinsic data quality metrics for OpenStreetMap data."
authors = ["ohsome team <ohsome@heigit.org>"]
homepage = "https://oqt.ohsome.org"
repository = "https://github.com/GIScience/ohsome-quality-analyst"
keywords = [
  "osm",
  "gis",
  "geography",
  "metric",
  "ohsome",
  "quality",
  ]

[tool.poetry.dependencies]
python = "~3.8"
geojson = "^2.5.0"
click = "^7.1.2"
fastapi = "^0.68.0"
uvicorn = "^0.12.2"
requests = "^2.25.0"
matplotlib = "^3.2.2"
pandas = "^1.1.5"
dacite = "^1.6.0"
PyYAML = "^5.4.1"
toml = "^0.10.2"
httpx = "^0.17.0"
asyncpg = "^0.22.0"
vcrpy = "^4.1.1"
python-dateutil = "^2.8.2"
scipy = "^1.7.1"
rpy2 = "^3.4.5"

[tool.poetry.dev-dependencies]
mypy = "0.790"
schema = "^0.7.3"
pytest = "^6.2.2"
isort = "5.9.3"
pytest-cov = "^2.12.0"
pep8-naming = "^0.12.1"
flake8 = "3.9.2"
black = "21.9b0"
pre-commit = "^2.15.0"

[tool.poetry.scripts]
oqt = "ohsome_quality_analyst.cli.cli:cli"

[tool.poetry.urls]
"Issues" = "https://github.com/GIScience/ohsome-quality-analyst/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
